services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
      POSTGRES_HOST: $DB_HOST
      POSTGRES_PORT: $DB_PORT
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data